file/urls.py
from django.urls import path
from . import views
 
app_name="file"

urlpatterns = [


    path("", views.indexpage, name="indexpage"),
   # path('student_login/', views.student_login, name="student_login"),
    path("userlogin/",views.userlogin,name="userlogin"),
    path("schoolreg/", views.schoolreg, name="schoolreg"),
    path('Package1/', views.Package1, name='Package1'),
    path('Package2/', views.Package2, name='Package2'),
    path('Package3/', views.Package3, name='Package3'),
    path('Package4/', views.Package4, name='Package4'),
    path('school_details_atl_incharge/', views.school_details_atl_incharge, name='school_details_atl_incharge'),
    path('schoolatlinchargeweb/', views.schoolatlinchargeweb, name='schoolatlinchargeweb'),
    path('AESWeb/', views.AESWeb, name='AESWeb'),
    path('TNFA/', views.TNFA, name='TNFA'),
    path("atl_login/", views.atl_login, name="atl_login"),
    path("venregweb/", views.venregweb, name="venregweb"),
    path("mentorofchangeweb/", views.mentorofchangeweb, name="mentorofchangeweb"),
    path('question/', views.question, name="question"),
     path('data/',views.data,name="data"),
    
    
]

file/views.py
from django.shortcuts import render, redirect
from django.template import loader, Context
from django.contrib.auth.models import User,auth


from django.urls import reverse
import sys
from django.contrib import auth
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from file.models import PackageOne, Packaget, Packageth, Packagef, schoolatlincharges, teachernominatedforatl, aes, \
    student_login_detail, AI_Questions, table, venreg1, moc


# labregistration page
def Package1(request):
    if request.method == 'POST':
        sel = request.POST.get('sel')
        other = request.POST.get('other')
        scope = request.POST.get('scope')
        days = request.POST.get('days')
        who = request.POST.get('who')
        if sel is not None or sel != "" or other is not None or other != "" or scope is not None or scope != "" or days is not None or days != "" or who is not None or who != "":
            pc1 = PackageOne(Electroniclist=sel, otherofferingsPleasespecify=other, Scopeoftraining=scope,
                             Noofdaysoftraining=days, Whoattendedtraining=who)
            pc1.save()
            # print(other,scope,days,who)
            return HttpResponseRedirect("/Package1")
        return HttpResponse('invalid')
    return render(request, 'regi.html')


def Package2(request):
    if request.method == 'POST':
        cel = request.POST.get('cel')
        other = request.POST.get('other')
        scope = request.POST.get('scope')
        days = request.POST.get('days')
        who = request.POST.get('who')
        if cel is not None or cel != "" or other is not None or other != "" or scope is not None or scope != "" or days is not None or days != "" or who is not None or who != "":
            pc2 = Packaget(Printer=cel, OtherOfferingsPleasespecify=other, Scopeoftraining=scope,
                           Noofdaysoftraining=days, Whoattendedtraining=who)
            pc2.save()
            return HttpResponseRedirect('/Package2')
        return HttpResponse('invalid')
    return render(request, 'package2.html')


def Package3(request):
    if request.method == 'POST':
        selv = request.POST.get('selv')
        other = request.POST.get('other')
        scope = request.POST.get('scope')
        days = request.POST.get('days')
        who = request.POST.get('who')
        if selv is not None or selv != "" or other is not None or other != "" or scope is not None or scope != "" or days is not None or days != "" or who is not None or who != "":
            pc3 = Packageth(Field=selv, Otherofspecify=other, Scopeoftraining=scope, Noofdaysoftraining=days,
                            Whoattendedtraining=who)
            pc3.save()
            return HttpResponseRedirect('/Package3')
        return HttpResponse('invalid')
    return render(request, 'package3.html')


def Package4(request):
    if request.method == 'POST':
        self = request.POST.get('self')
        other = request.POST.get('other')
        scope = request.POST.get('scope')
        days = request.POST.get('days')
        who = request.POST.get('who')
        print(self, other, scope, days, who)
        if self is not None or self != "" or other is not None or other != "" or scope is not None or scope != "" or days is not None or days != "" or who is not None or who != "":
            pc4 = Packagef(Safety=self, OtherOfferingsPleasespecify=other, Scopeoftraining=scope,
                           Noofdaysoftraining=days, Whoattendedtraining=who)
            pc4.save()
            return HttpResponseRedirect('/Package4')

        return HttpResponse('invalid')
    return render(request, 'package4.html')


def userlogin(request):

    if request.method == "POST":
        ValMobilenumber = request.POST.get("Mobilenumber")
        # studentid = request.POST.get("studentid")
        # username = request.POST.get("username")
        Valpassword = request.POST.get("password")
        # username=getattr(object,'username')
        list = student_login_detail.objects.get(Mobilenumber=ValMobilenumber)

        username = list.username
        request.session['username'] = username
        print(username)
        # username = request.session['username']
        print(ValMobilenumber, Valpassword, username)
        try:

            if student_login_detail.objects.filter(Mobilenumber=ValMobilenumber).exists():
                db = student_login_detail.objects.get(Mobilenumber=ValMobilenumber)
                if db.Mobilenumber == ValMobilenumber:
                    if db.Mobilenumber == ValMobilenumber and db.password == Valpassword:
                        return HttpResponseRedirect("/userlogin", {"username": username})
                    return HttpResponse("Invalid Credentials")
            elif student_login_detail.objects.filter(email=ValMobilenumber).exists():
                db = student_login_detail.objects.get(email=ValMobilenumber)
                if db.email == ValMobilenumber and db.password == Valpassword:
                    return HttpResponseRedirect("/userlogin", {"username": username})
                return HttpResponse("Invalid Credentials")
        except Exception as e:
            print(e)
            return HttpResponse("No Value Found")
    return render(request, "index1.html")

def indexpage(request):
    return render(request, "index.html" )

'''def userlogin(request):
    print("in the userlogin")
    return render(request, "userlogin.html" )'''

def schoolreg(request):
    print("in the schoolreg")
    return render(request, "schoolreg.html", )

    def schoolreg(request):
        return render(request, "index2.html")

    def schoolreg(request):
        return render(request, "index3.html")


def atl_login(request):
    return render(request, "schoolreg.html")


def vendorreg(request):
    return render(request, "vendor.html")


def mentorofchange(request):
    return render(request, "mentorofchange.html")


def school_details_atl_incharge(request):
    if request.method == "POST":
        school_name = request.POST.get("school_name")
        school_reg_id = request.POST.get("school_reg_id")
        country = request.POST.get("country")
        state = request.POST.get("state")
        district = request.POST.get("district")
        pincode = request.POST.get("pincode")
        phone = request.POST.get("phone")
        Email = request.POST.get("Email")
        affilation_body = request.POST.get("affilation_body")
        print(school_name, school_reg_id, country, state, district, pincode, phone, Email, affilation_body)
        try:

            ram = school_details_atl_incharge(school_name=school_name, school_reg_id=school_reg_id, country=country,
                                              state=state, district=district, pincode=pincode, phone=phone, Email=Email,
                                              affiliation_body=affilation_body)
            print(school_name, school_reg_id, country, state, district, pincode, phone, Email, affilation_body)
            ram.save()
            return HttpResponseRedirect("/school_details_atl_incharge/")
        except Exception as e:
            print(e)

            return HttpResponse("Error")
    return render(request, "index1.html")


def schoolatlinchargeweb(request):
    if request.method == "POST":
        valpersonname = request.POST.get("personname")
        valpersonID = request.POST.get("personID")
        valmobile = request.POST.get("mobile")
        valemail = request.POST.get("email")
        print(valpersonname, valpersonID, valmobile, valemail)
        try:
            print("Try Sction")
            val = schoolatlincharges(personname=valpersonname, personID=valpersonID, mobile=valmobile, email=valemail)
            val.save()
            return HttpResponseRedirect("/schoolatlinchargeweb/")
        except Exception as e:
            print(e)
            return HttpResponse("invaliduser")
    return render(request, "index2.html")


def AESWeb(request):
    if request.method == "POST":
        option1 = request.POST.get("option1")
        date1 = request.POST.get("date1")
        name = request.POST.get("name")
        number = request.POST.get("number")
        email = request.POST.get("email")
        option2 = request.POST.get("option2")
        date2 = request.POST.get("date2")
        option3 = request.POST.get("option3")
        date3 = request.POST.get("date3")
        print(option1, date1, name, number, email, option2, date2, option3, date3)
        try:
            val = aes(option1=option1, date1=date1, name=name, number=number, email=email, option2=option2, date2=date2,
                      option3=option3, date3=date3)
            val.save()
            return HttpResponseRedirect("/AESWeb/")
        except Exception as e:
            return HttpResponse("Invalid......")
    return render(request, "index3.html")


def TNFA(request):
    if request.method == "POST":
        vname = request.POST.get("name")
        vphone = request.POST.get("number")
        vemailid = request.POST.get("email")
        try:
            val = teachernominatedforatl(name=vname, phone=vphone, emailid=vemailid)
            val.save()
            return HttpResponseRedirect("/TNFA/")
        except Exception as e:
            return HttpResponse("invaliduserpass")
    return render(request, "index4.html")


def question(request):
    ques1 = AI_Questions.objects.get(id=1)
    ques2 = AI_Questions.objects.get(id=2)
    ques3 = AI_Questions.objects.get(id=3)
    ques4 = AI_Questions.objects.get(id=4)
    ques5 = AI_Questions.objects.get(id=5)
    context = {
        'obj1': ques1,
        'obj2': ques2,
        'obj3': ques3,
        'obj4': ques4,
        'obj5': ques5,
    }
    return render(request, 'quiz.html', {'context': context})


def data(request):
    record = table.objects.get(id=2)
    content = {
        'object': record
    }

file/templates/index1.html
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
        <title>AI Assessment Tool</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
        <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
        <meta name="author" content="Codrops" />
        
        <link rel="stylesheet" type="text/css" href="/static/css/css/demo.css" />
        <link rel="stylesheet" type="text/css" href="/static/css/css/style.css" />
        <link rel="stylesheet" type="text/css" href="/static/css/css/animate-custom.css" />
        <style>
            .row{
                margin: 1% 0%; 
                width: 100%;
                display: inline-flex;
				align-items: center;
                }
            .col-25 {
                width: 34%;
                margin-top: 6px;
             }
            .col-75 {
            width: 66%;
            margin-top: 6px;
            }
        </style>
    </head>
    <body>
        <div class="container">
           
            <header>
                <h1>School ATL Incharge </h1>

                <br><h1 style="text-align:left;"><a href="{% url 'file:userlogin'%}">HOME</a></h1>


                <span>Welcome {{ request.session.username }}</span>

				<nav class="codrops-demos">
					
					<a href="{% url 'file:school_details_atl_incharge' %}" class="current-demo"><br>School Details for ATL Incharge</a>
					<a href="{% url 'file:schoolatlinchargeweb' %}"><br>School ATL Incharge Information</a>
                    <a href="{% url 'file:AESWeb' %}"><br>ATL Establishment Status</a>
                    <a href="{% url 'file:TNFA'%}"><br>Teacher Nomination Details</a>
				</nav>
            </header>
            <section>				
                <div id="container_demo" >
                    <a class="hiddenanchor" id="toregister"></a>
                    <a class="hiddenanchor" id="tologin"></a>
                    <div id="wrapper">
                        <div id="login" class="animate form">
                            <form  autocomplete="on"  method="POST" onsubmit="return save()">
                                {% csrf_token %}
                                <h1>School Details</h1> 
                                <div class="row">
                                    <div class="col-25">
                                        <label for="schoolname" class="uname" >1. School Name </label>
                                    </div>
                                    <div class="col-75">
                                        <input id="schname" name="school_name" required="required" type="text" placeholder="School Name"/>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="schid" class="youpasswd" >2. School Registration ID </label>
                                    </div>
                                    <div class="col-75">
                                        <input id="schregID" name="school_reg_id" required="required" type="text" placeholder="School Registration ID" />
                                    </div>
                                </div>
                                <div class="row">
                                    
                                        <label for="address" class="address" > <b>3. Address Details</b></label><br><br>
                                    
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="country" class="country" > &nbsp;&nbsp;&nbsp; Country Name </label>
                                    </div>
                                    <div class="col-75">
                                        <input id="country" name="country" required="required" type="text" placeholder="Country" /> 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="state" class="state" > &nbsp;&nbsp;&nbsp;State    </label>
                                    </div>
                                    <div class="col-75">
                                        <input id="state" name="state" required="required" type="text" placeholder="State" /> 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="city" class="city" >&nbsp;&nbsp;&nbsp;City/<br>&nbsp;&nbsp;&nbsp;District</label>
                                    </div>
                                    <div class="col-75">
                                        <input id="city" name="district" required="required" type="text" placeholder="City/District" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="pincode" class="pincode" >&nbsp;&nbsp;&nbsp;Pin Code</label>
                                    </div>
                                    <div class="col-75">
                                        <input id="pincode" name="pincode" required="required" type="text" placeholder="Pin Code" /> 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="phone" class="phone" >4. Phone Number</label>
                                    </div>
                                    <div class="col-75">
                                        <input id="phone" name="phone" required="required" type="text" placeholder="Phone Number" /> 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="email" class="email" >5. Email ID</label>
                                    </div>
                                    <div class="col-75">
                                        <input id="email" name="Email" required="required" type="text" placeholder="Email ID" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="affiliation" class="affiliation" >6.Affiliation Body</label><br>
                                    </div>
                                    <div class="col-75">
                                        <input id="cbse" name="affilation_body" type="radio" value="CBSE" />CBSE
                                    
                                        <input id="icse" name="affilation_body" type="radio" value="ICSE" />ICSE
                                    
                                        <input id="state_board" name="affilation_body" type="radio" value="State Board"/>State Board
                                    
                                        <input id="other" name="affilation_body" type="radio" />Other Board
                                        <div class="col-75">
                                            <input type="text" class="board" id="board" placeholder="Other board"/>
                                        </div>
                                    
                                    </div>
                                </div>
                                <footer >
                                    <p class="login button"><input type="submit" value="Save" name="submit" class="login" onsubmit="save()"/> </p>
                                    <p class="login button"><a href="{% url 'file:schoolatlinchargeweb' %}"><input type="button" value="Next"  /></a> </p>
                                   <p class="login button"><a href="{% url 'file:schoolreg'%}"><input type="button" value="Cancel"  /></a> </p>
                            </footer>
                            </form>

                        </div>
                    </div>
                </div>  
            </section>       
        </div>
        <script>
            function save(){
                //alert("Data saved successfully")
            }
        </script>
    </body>
</html>

file/templates/index3.html
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
        <title>Login and Registration Form with HTML5 and CSS3</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
        <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
        <meta name="author" content="Codrops" />
        <link rel="shortcut icon" href="../favicon.ico"> 
        <link rel="stylesheet" type="text/css" href="/static/css/css/demo.css" />
        <link rel="stylesheet" type="text/css" href="/static/css/css/style3.css" />
        <link rel="stylesheet" type="text/css" href="/static/css/css/animate-custom.css" />
      <style>
        .row{
            margin: 1% 0%; 
            width: 100%;
            display: inline-flex;
            }
        .col-25 {
            width: 34%;
            margin-top: 6px;
         }
        .col-75 {
        width: 66%;
        margin-top: 6px;
        }
    </style>
    </head>
    <body>
        <div class="container">
               
            <header>
                <h1>School ATL Incharge </h1>
                <span>Welcome username</span>
                <nav class="codrops-demos">
                    
                    <a href=<a href="{% url 'file:school_details_atl_incharge' %}" ><br>School Details for ATL Incharge</a>
                    <a href="{% url 'file:schoolatlinchargeweb' %}" ><br>School ATL Incharge Information</a>
                    <a href="{% url 'file:AESWeb' %}" class="current-demo"><br>ATL Establishment Status</a>
                    <a href="{% url 'file:TNFA'%}"><br>Teacher Nomination Details</a>
                </nav>
            </header>
            <section>				
                <div id="container_demo" >
                    
                    
                    <div id="wrapper">
                        <div id="login" class="animate form">
                            <form  autocomplete="on" method="POST"> 
                                {% csrf_token %}
                                <h1>ATL Establishment Status</h1> 

                                <div class="row">
                                     <div class="col-25">
                                        <label for="applied" class="applied" >1. Has applied for ATL Lab</label><br>
                                    </div>
									
                                    <div class="col-75">
                                        &nbsp;&nbsp;&nbsp;<input id="option1" name="option1" value="yes" type="radio" />Yes
                                        &nbsp;&nbsp;&nbsp;<input id="option1" name="option1" value="no" type="radio" />No                                  
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="whichdate" class="whichdate" >&nbsp;&nbsp;&nbsp; Which Date </label>
                                    </div>
                                    <div class="col-75">
                                        <input id="date1" name="date1" required="required" type="datetime" placeholder="Date" /> 
                                    </div>
                                </div>
                                <div class="row">
                                    
                                        <label for="registered" class="registered" > <b>2. Who Registered?</b></label><br><br>
                                    
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="name" class="name" >&nbsp;&nbsp;&nbsp;Name</label>
                                    </div>
                                    <div class="col-75">
                                        <input id="name" name="name" required="required" type="text" placeholder="Name" /> 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="number" class="number" >&nbsp;&nbsp;&nbsp;Contact Number</label>
                                    </div>
                                    <div class="col-75">
                                        <input id="number" name="number" required="required" type="text" placeholder="Number" /> 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="email" class="email" >&nbsp;&nbsp;&nbsp;Email ID</label>
                                    </div>
                                    <div class="col-75">
                                        <input id="email" name="email" required="required" type="text" placeholder="Email" /> 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="qualified" class="qualified" >3. Has ATL got selected or qualified</label><br>
                                    </div>
                                    <div class="col-75">
                                       &nbsp;&nbsp;&nbsp; <input id="option2" name="option2" value="yes" type="radio" />Yes
                                       &nbsp;&nbsp;&nbsp; <input id="option2" name="option2" value="no" type="radio" />No                                 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="whichdate1" class="whichdate1" >&nbsp;&nbsp;&nbsp; Which Date </label>
                                    </div>
                                    <div class="col-75">
                                        <input id="date2" name="date2" required="required" type="datetime" placeholder="Date" /> 
                                    </div>
                                </div>
                                <div class="row">
                                     <div class="col-25">
                                        <label for="fund" class="fund" >4. Has ATL Fund Received</label><br>
                                    </div>
									
                                    <div class="col-75">
                                        &nbsp;&nbsp;&nbsp;<input id="option3" name="option3" value="yes" type="radio" />Yes
                                        &nbsp;&nbsp;&nbsp;<input id="option3" name="option3" value="no" type="radio" />No                                 
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-25">
                                        <label for="whichdate2" class="whichdate2" >&nbsp;&nbsp;&nbsp; Which Date </label>
                                    </div>
                                    <div class="col-75">
                                        <input id="date3" name="date3" required="required" type="datetime" placeholder="Date" /> 
                                    </div>
                                </div>
                                <footer >                  
                                    <p class="login button"><input type="submit" value="Save" name="submit" class="login"/> </p>
                                    <p class="login button"><a href="{% url 'file:schoolatlinchargeweb' %}"><input type="button" value="Previous"  /></a> </p>
                                    <p class="login button"><a href="{% url 'file:TNFA'%}"><input type="button" value="Next"  /></p></a> 
                                    <p class="login button"><a href="{% url 'file:schoolreg'%}"><input type="button" value="Cancel"  /></a> </p>
                            </footer>
                            </form>
                        </div>         
                    </div>
                </div>  
            </section>       
        </div>
    </body>
</html>